name: Sync LeetCode Submissions

on:
  workflow_dispatch:   # manual trigger
  schedule:
    - cron: "0 2 * * *" # runs daily at 2 AM UTC

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync LeetCode
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-username: ${{ secrets.LEETCODE_USERNAME }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          destination-folder: "leetcode"
          verbose: true
